-- ************************* SqlDBM: PostgreSQL *************************
-- ****** Generated by SqlDBM: Workshop, v46 by Finn1435@rambler.ru *****

-- ************************************** barcode

CREATE TABLE barcode
(
    barcode_id  NOT NULL,
    barcode    integer NOT NULL,
    CONSTRAINT PK_barcode PRIMARY KEY ( barcode_id )
);


CREATE TABLE element_firma
(
    "id"          NOT NULL,
    firma_id   integer NOT NULL,
    element_id integer NOT NULL,
    CONSTRAINT PK_element_firma PRIMARY KEY ( "id" ),
    CONSTRAINT FK_11_2 FOREIGN KEY ( firma_id ) REFERENCES firma ( firma_id ),
    CONSTRAINT FK_12_1 FOREIGN KEY ( element_id ) REFERENCES "public"."element" ( element_id ),
    CONSTRAINT FK_13 FOREIGN KEY ( "id" ) REFERENCES barcode ( barcode_id )
);

CREATE INDEX FK_1 ON element_firma
(
    firma_id
);

CREATE INDEX FK_2 ON element_firma
(
    element_id
);

CREATE INDEX FK_3 ON element_firma
(
    "id"
);

CREATE TABLE element_groups
(
    "id"         integer NOT NULL,
    element_id integer NULL,
    group_id   integer NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( id ),
    CONSTRAINT FK_11 FOREIGN KEY ( element_id ) REFERENCES "public"."element" ( element_id ),
    CONSTRAINT FK_12 FOREIGN KEY ( group_id ) REFERENCES "public".groups ( group_id )
);

CREATE INDEX FK_1 ON element_groups
(
    element_id
);

CREATE INDEX FK_2 ON element_groups
(
    group_id
);


CREATE TABLE elements_composite
(
    id                  integer NOT NULL,
    element_source      integer NULL,
    element_destination integer NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( id ),
    CONSTRAINT FK_14 FOREIGN KEY ( element_source ) REFERENCES "public"."element" ( element_id ),
    CONSTRAINT FK_15 FOREIGN KEY ( element_destination ) REFERENCES "public"."element" ( element_id )
);

CREATE INDEX FK_1 ON elements_composite
(
    element_source
);

CREATE INDEX FK_2 ON elements_composite
(
    element_destination
);


CREATE TABLE firma
(
    firma_id  integer NOT NULL,
    firm_name character(50) NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( firma_id )
);


CREATE TABLE "public".attribute
(
    name           character(50) NOT NULL,
    attribute_id   integer NOT NULL,
    attribute_id_1 integer NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( attribute_id_1 ),
    CONSTRAINT FK_11_1 FOREIGN KEY ( attribute_id ) REFERENCES "public".attribute_value ( attribute_id )
);

CREATE INDEX FK_1 ON "public".attribute
(
    attribute_id
);


CREATE TABLE "public".attribute_double_value
(
    attribute_id integer NOT NULL,
    value        real NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( attribute_id )
);

CREATE TABLE "public".attribute_integer_value
(
    attribute_id integer NOT NULL,
    value        integer NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( attribute_id ),
    CONSTRAINT FK_7_1 FOREIGN KEY ( attribute_id ) REFERENCES "public".attribute_value ( attribute_id )
);

CREATE INDEX FK_1 ON "public".attribute_integer_value
(
    attribute_id
);

CREATE TABLE "public".attribute_string_value
(
    attribute_id integer NOT NULL,
    value        character NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( attribute_id )
);

CREATE TABLE "public".attribute_value
(
    attribute_id          integer NOT NULL,
    name                  character NOT NULL,
    group_attr_value_id   integer NULL,
    element_attr_value_id integer NOT NULL,
    CONSTRAINT attribute_pkey PRIMARY KEY ( attribute_id ),
    CONSTRAINT unique_attr_name_constraint UNIQUE ( name ),
    CONSTRAINT FK_9_2 FOREIGN KEY ( group_attr_value_id ) REFERENCES "public".groups ( group_id ),
    CONSTRAINT FK_9_3 FOREIGN KEY ( element_attr_value_id ) REFERENCES "public"."element" ( element_id )
);

CREATE INDEX FK_2 ON "public".attribute_value
(
    group_attr_value_id
);

CREATE INDEX FK_2_1 ON "public".attribute_value
(
    element_attr_value_id
);

CREATE TABLE "public"."element"
(
    element_id  integer NOT NULL,
    name        character NOT NULL,
    description character NULL,
    parent_id   integer NULL,
    CONSTRAINT component_pkey PRIMARY KEY ( element_id ),
    CONSTRAINT unique_component_name_constraint UNIQUE ( name ),
    CONSTRAINT FK_10 FOREIGN KEY ( parent_id ) REFERENCES "public"."element" ( element_id )
);

CREATE INDEX FK_2 ON "public"."element"
(
    parent_id
);

CREATE TABLE "public".groups
(
    group_id   integer NOT NULL,
    group_name character NOT NULL,
    parent_id  integer NULL,
    CONSTRAINT PK_1 PRIMARY KEY ( group_id ),
    CONSTRAINT FK_10_1 FOREIGN KEY ( parent_id ) REFERENCES "public".groups ( group_id )
);

CREATE INDEX FK_1 ON "public".groups
(
    parent_id
);