<#macro description>

        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description :</label>
            <div class="col-sm-6">
                <textarea
                        class="form-control"
                        name="description"
                        placeholder="Description"
                        maxlength=800
                        id="desk">
                </textarea>
            </div>
        </div>

</#macro>
