<#import "parts/common.ftlh" as c>

<@c.page>
    <a href="/storage/contragent">Contragent</a>
        <br />
    <a href="/storage/storage">Storage</a>
        <br />
    <a href="/storage/workshop">Workshop</a>
        <br />
    <a href="/storage/goods">Goods</a>
        <br />
    <a href="/storage/arrival">Arrival Goods</a>
        <br />
    <a href="/storage/expense">Expense Goods</a>
        <br />
    <a href="/storage/contragents_party">Contragents party</a>
        <br />

</@c.page>