-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.attribute
(
    attribute_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    unit smallint,
    CONSTRAINT attribute_pkey PRIMARY KEY (attribute_id),
    CONSTRAINT uk_hpwum0iq12fs4ej5d0tgy6wsn UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.attribute_integer_value
(
    attr_int_id integer NOT NULL,
    value integer,
    CONSTRAINT attribute_integer_value_pkey PRIMARY KEY (attr_int_id)
);

CREATE TABLE IF NOT EXISTS public.attribute_string_value
(
    attr_str_val integer NOT NULL,
    value character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT attribute_string_value_pkey PRIMARY KEY (attr_str_val)
);

CREATE TABLE IF NOT EXISTS public.component
(
    component_id integer NOT NULL,
    description character varying(2048) COLLATE pg_catalog."default",
    is_composite boolean,
    is_electric boolean,
    is_electronic boolean,
    is_mechanic boolean,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT component_pkey PRIMARY KEY (component_id),
    CONSTRAINT uk_qkg4faf5v8maop4avw1y44cxp UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.component_attribute
(
    comp_id integer NOT NULL,
    attr_id integer NOT NULL,
    CONSTRAINT component_attribute_pkey PRIMARY KEY (attr_id, comp_id)
);

CREATE TABLE IF NOT EXISTS public.component_relationship
(
    parent_id integer NOT NULL,
    child_id integer NOT NULL,
    CONSTRAINT component_relationship_pkey PRIMARY KEY (parent_id, child_id)
);

CREATE TABLE IF NOT EXISTS public.equipment
(
    equipment_id integer NOT NULL,
    firm_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    model character varying(128) COLLATE pg_catalog."default" NOT NULL,
    type character varying(128) COLLATE pg_catalog."default",
    gr_id integer,
    CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id, gr_id),
    CONSTRAINT uk_brtfbdlnplo93o187lw1ffwch UNIQUE (model)
);

CREATE TABLE IF NOT EXISTS public.equipment_component
(
    equip_id integer NOT NULL,
    comp_id integer NOT NULL,
    CONSTRAINT equipment_component_pkey PRIMARY KEY (comp_id, equip_id)
);

CREATE TABLE IF NOT EXISTS public.flyway_schema_history
(
    installed_rank integer NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    script character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    checksum integer,
    installed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    installed_on timestamp without time zone NOT NULL DEFAULT now(),
    execution_time integer NOT NULL,
    success boolean NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE IF NOT EXISTS public.groups
(
    group_id integer NOT NULL,
    group_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT groups_pkey PRIMARY KEY (group_id)
);

ALTER TABLE IF EXISTS public.component_attribute
    ADD CONSTRAINT fka5ind1xk928ifei5b785k9bd FOREIGN KEY (attr_id)
    REFERENCES public.attribute (attribute_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.component_attribute
    ADD CONSTRAINT fksx6ga5rf0qp56i5qpoqfl8tl9 FOREIGN KEY (comp_id)
    REFERENCES public.component (component_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.component_relationship
    ADD CONSTRAINT fk5yxq9pvdd4r6kms60skpii3ge FOREIGN KEY (child_id)
    REFERENCES public.component (component_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.component_relationship
    ADD CONSTRAINT fkpqrutnghvfevw4khdujy6d22b FOREIGN KEY (parent_id)
    REFERENCES public.component (component_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipment_component
    ADD CONSTRAINT fk4pnhrdnj55cgb8h8r5dtleqm6 FOREIGN KEY (equip_id)
    REFERENCES public.equipment (equipment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipment_component
    ADD CONSTRAINT fkce2uhg91nxk9npcnf88501ca4 FOREIGN KEY (comp_id)
    REFERENCES public.component (component_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.groups
    ADD CONSTRAINT group_id FOREIGN KEY (group_id)
    REFERENCES public.equipment (gr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;