--
-- TOC entry 3463 (class 0 OID 324585)
-- Dependencies: 218
-- Data for Name: element_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.element_groups VALUES (1, 1);
INSERT INTO public.element_groups VALUES (3, 1);
INSERT INTO public.element_groups VALUES (4, 1);
INSERT INTO public.element_groups VALUES (5, 4);
INSERT INTO public.element_groups VALUES (6, 4);
INSERT INTO public.element_groups VALUES (7, 4);
INSERT INTO public.element_groups VALUES (8, 4);
INSERT INTO public.element_groups VALUES (54, 1);
INSERT INTO public.element_groups VALUES (55, 4);
INSERT INTO public.element_groups VALUES (56, 4);
INSERT INTO public.element_groups VALUES (57, 4);
INSERT INTO public.element_groups VALUES (58, 4);
INSERT INTO public.element_groups VALUES (59, 4);
INSERT INTO public.element_groups VALUES (60, 4);
INSERT INTO public.element_groups VALUES (61, 4);
INSERT INTO public.element_groups VALUES (63, 4);
INSERT INTO public.element_groups VALUES (62, 4);
INSERT INTO public.element_groups VALUES (64, 4);
INSERT INTO public.element_groups VALUES (65, 4);
INSERT INTO public.element_groups VALUES (66, 4);
INSERT INTO public.element_groups VALUES (67, 1);
INSERT INTO public.element_groups VALUES (68, 1);
INSERT INTO public.element_groups VALUES (69, 1);
INSERT INTO public.element_groups VALUES (70, 1);
INSERT INTO public.element_groups VALUES (71, 1);
INSERT INTO public.element_groups VALUES (72, 1);
INSERT INTO public.element_groups VALUES (73, 1);
INSERT INTO public.element_groups VALUES (74, 1);
INSERT INTO public.element_groups VALUES (75, 1);
INSERT INTO public.element_groups VALUES (76, 1);
INSERT INTO public.element_groups VALUES (77, 1);
INSERT INTO public.element_groups VALUES (78, 1);
INSERT INTO public.element_groups VALUES (79, 1);
INSERT INTO public.element_groups VALUES (80, 1);
INSERT INTO public.element_groups VALUES (82, 4);
INSERT INTO public.element_groups VALUES (90, 1);
INSERT INTO public.element_groups VALUES (91, 1);
INSERT INTO public.element_groups VALUES (92, 1);
INSERT INTO public.element_groups VALUES (93, 1);
INSERT INTO public.element_groups VALUES (94, 1);
INSERT INTO public.element_groups VALUES (95, 1);
INSERT INTO public.element_groups VALUES (96, 1);
INSERT INTO public.element_groups VALUES (97, 1);
INSERT INTO public.element_groups VALUES (98, 1);
INSERT INTO public.element_groups VALUES (99, 1);
INSERT INTO public.element_groups VALUES (102, 1);
INSERT INTO public.element_groups VALUES (103, 1);
INSERT INTO public.element_groups VALUES (104, 1);
INSERT INTO public.element_groups VALUES (105, 1);
INSERT INTO public.element_groups VALUES (106, 1);
INSERT INTO public.element_groups VALUES (109, 1);
INSERT INTO public.element_groups VALUES (110, 1);
INSERT INTO public.element_groups VALUES (153, 6);
INSERT INTO public.element_groups VALUES (202, 4);
INSERT INTO public.element_groups VALUES (203, 4);
INSERT INTO public.element_groups VALUES (204, 4);
INSERT INTO public.element_groups VALUES (252, 1);
INSERT INTO public.element_groups VALUES (253, 1);
INSERT INTO public.element_groups VALUES (254, 1);
INSERT INTO public.element_groups VALUES (255, 1);
INSERT INTO public.element_groups VALUES (52, 4);
INSERT INTO public.element_groups VALUES (256, 4);
INSERT INTO public.element_groups VALUES (257, 4);